export const GET_COMMENT_BY_PASSENGER = "GET_COMMENT_BY_PASSENGER";
export const GET_COMMENT_BY_USER = "GET_COMMENT_BY_USER";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
